version: "3"
services:
  delta-consumer:
    build:
      context: ./delta_reader
      dockerfile: Dockerfile
    networks:
      - wikiflow-network
    ports:
      - "4041:4040"
    volumes:
      - delta:/storage
networks:
  wikiflow-network:
    external:
      name: wikiflow-network
volumes:
  delta: