SELECT *
FROM spark_sandbox_db.crimes LIMIT 10;

truncate table crimes

SELECT 
	IF(crimes.DISTRICT LIKE '', 'UNKNOWN', crimes.DISTRICT)	AS DISTRICT
	,COUNT(INCIDENT_NUMBER)									AS CRIMES_TOTAL_PER_DISTRICT
	,AVG(LATITUDE)											AS AVG_LATITUDE
	,AVG(LONGITUDE)											AS AVG_LONGITUDE
FROM crimes AS crimes
GROUP BY crimes.DISTRICT

========================================================================================


SELECT DISTINCT 
	DISTRICT AS DISTRICT,
	CONCAT_WS(', ', CONCAT(FREQ_CRIME_TYPE_CODE_1,' : ',CRIMES_OF_TYPE_COUNT_1), CONCAT(FREQ_CRIME_TYPE_CODE_2,' : ',CRIMES_OF_TYPE_COUNT_2), CONCAT(FREQ_CRIME_TYPE_CODE_3,' : ',CRIMES_OF_TYPE_COUNT_3)) AS CRIMES_TOP_3
FROM 
(
	SELECT
		DISTRICT																					 						AS DISTRICT,
		NTH_VALUE(CRIME_TYPE_CODE,1)			OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT DESC)			 	AS FREQ_CRIME_TYPE_CODE_1,
		NTH_VALUE(CRIMES_OF_TYPE_COUNT,1)		OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT DESC) 			AS CRIMES_OF_TYPE_COUNT_1,
		NTH_VALUE(CRIME_TYPE_CODE,2)			OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT DESC)			 	AS FREQ_CRIME_TYPE_CODE_2,
		NTH_VALUE(CRIMES_OF_TYPE_COUNT,2)		OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT DESC) 			AS CRIMES_OF_TYPE_COUNT_2,
		NTH_VALUE(CRIME_TYPE_CODE,3)			OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT DESC)			 	AS FREQ_CRIME_TYPE_CODE_3,
		NTH_VALUE(CRIMES_OF_TYPE_COUNT,3)		OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT DESC) 			AS CRIMES_OF_TYPE_COUNT_3
	FROM (
		SELECT
			IF(crimes.DISTRICT LIKE '', 'UNKNOWN', crimes.DISTRICT)					AS DISTRICT,
			COUNT(INCIDENT_NUMBER) OVER (PARTITION BY DISTRICT)						AS CRIMES_TOTAL_PER_DISTRICT,				
			OFFENSE_CODE															AS CRIME_TYPE_CODE,
			COUNT(INCIDENT_NUMBER) OVER (PARTITION BY DISTRICT, OFFENSE_CODE)		AS CRIMES_OF_TYPE_COUNT
		FROM crimes
	) AS CRIME_TYPES_PER_DISTRICT_STAT
) AS PREPARED_TABLE
WHERE FREQ_CRIME_TYPE_CODE_2 IS NOT NULL AND FREQ_CRIME_TYPE_CODE_3 IS NOT NULL 


===========================================================================================


SELECT
	IF(crimes.DISTRICT LIKE '', 'UNKNOWN', crimes.DISTRICT)					AS DISTRICT,
	COUNT(INCIDENT_NUMBER) OVER (PARTITION BY DISTRICT)						AS CRIMES_TOTAL_PER_DISTRICT,				
	OFFENSE_CODE															AS CRIME_TYPE_CODE,
	COUNT(INCIDENT_NUMBER) OVER (PARTITION BY DISTRICT, OFFENSE_CODE)		AS CRIMES_OF_TYPE_COUNT
FROM crimes

==============================================================================================

-- CRIMES_COUNT_PER_DISTRICT
SELECT
	IF(crimes.DISTRICT LIKE '', 'UNKNOWN', crimes.DISTRICT)					AS DISTRICT,
	COUNT(INCIDENT_NUMBER) 													AS CRIMES_TOTAL_PER_DISTRICT
FROM crimes
GROUP BY DISTRICT

-- CRIMES_COUNT_PER_DISTRICT_AND_CRIME_TYPE
SELECT
	IF(crimes.DISTRICT LIKE '', 'UNKNOWN', crimes.DISTRICT)					AS DISTRICT,	
	OFFENSE_CODE															AS CRIME_TYPE_CODE,
	COUNT(INCIDENT_NUMBER) 													AS CRIMES_OF_TYPE_COUNT
FROM crimes
GROUP BY DISTRICT, OFFENSE_CODE

--  
SELECT
	CRIMES_COUNT_PER_DISTRICT.DISTRICT										AS DISTRICT,
	CRIMES_COUNT_PER_DISTRICT.CRIMES_TOTAL_PER_DISTRICT						AS CRIMES_TOTAL_PER_DISTRICT,
	CRIMES_COUNT_PER_DISTRICT_AND_CRIME_TYPE.OFFENSE_CODE					AS CRIME_TYPE_CODE,
	COUNT(CRIMES_COUNT_PER_DISTRICT_AND_CRIME_TYPE.INCIDENT_NUMBER) 		AS CRIMES_OF_TYPE_COUNT_PER_DISTRICT
FROM crimes AS CRIMES_COUNT_PER_DISTRICT_AND_CRIME_TYPE
LEFT JOIN (
	SELECT
		IF(crimes.DISTRICT LIKE '', 'UNKNOWN', crimes.DISTRICT)				AS DISTRICT,
		COUNT(INCIDENT_NUMBER) 												AS CRIMES_TOTAL_PER_DISTRICT
	FROM crimes
	GROUP BY DISTRICT
) AS CRIMES_COUNT_PER_DISTRICT ON CRIMES_COUNT_PER_DISTRICT.DISTRICT LIKE CRIMES_COUNT_PER_DISTRICT_AND_CRIME_TYPE.DISTRICT 
GROUP BY DISTRICT, CRIMES_TOTAL_PER_DISTRICT, CRIME_TYPE_CODE

-- 

SELECT DISTINCT
	DISTRICT 																		AS DISTRICT,
	CRIMES_TOTAL_PER_DISTRICT 														AS CRIMES_TOTAL_PER_DISTRICT,
	AVG_CRIME_LATITUDE_PER_DISTRICT 												AS AVG_CRIME_LATITUDE_PER_DISTRICT,
	AVG_CRIME_LONGITUDE_PER_DISTRICT 												AS AVG_CRIME_LONGITUDE_PER_DISTRICT,
	CONCAT_WS(', ', 
		CONCAT(REGEXP_REPLACE(FREQ_CRIME_TYPE_1,'\s*-.*',''),'(',CRIMES_OF_TYPE_COUNT_PER_DISTRICT_1,')'), 
		CONCAT(REGEXP_REPLACE(FREQ_CRIME_TYPE_2,'\s*-.*',''),'(',CRIMES_OF_TYPE_COUNT_PER_DISTRICT_2,')'), 
		CONCAT(REGEXP_REPLACE(FREQ_CRIME_TYPE_3,'\s*-.*',''),'(',CRIMES_OF_TYPE_COUNT_PER_DISTRICT_3,')')) 	AS CRIMES_TOP_3
FROM 
(
	SELECT 
		STAT_PER_DISTRICT_AND_CRIME_TYPES.DISTRICT																					 		AS DISTRICT,
		STAT_PER_DISTRICT_AND_CRIME_TYPES.CRIMES_TOTAL_PER_DISTRICT 																		AS CRIMES_TOTAL_PER_DISTRICT,
		STAT_PER_DISTRICT_AND_CRIME_TYPES.AVG_CRIME_LATITUDE_PER_DISTRICT																	AS AVG_CRIME_LATITUDE_PER_DISTRICT,
		STAT_PER_DISTRICT_AND_CRIME_TYPES.AVG_CRIME_LONGITUDE_PER_DISTRICT 																	AS AVG_CRIME_LONGITUDE_PER_DISTRICT,
		NTH_VALUE(CRIME_TYPE,1)								OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT_PER_DISTRICT DESC)	AS FREQ_CRIME_TYPE_1,
		NTH_VALUE(CRIMES_OF_TYPE_COUNT_PER_DISTRICT,1)		OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT_PER_DISTRICT DESC) 	AS CRIMES_OF_TYPE_COUNT_PER_DISTRICT_1,
		NTH_VALUE(CRIME_TYPE,2)								OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT_PER_DISTRICT DESC)	AS FREQ_CRIME_TYPE_2,
		NTH_VALUE(CRIMES_OF_TYPE_COUNT_PER_DISTRICT,2)		OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT_PER_DISTRICT DESC) 	AS CRIMES_OF_TYPE_COUNT_PER_DISTRICT_2,
		NTH_VALUE(CRIME_TYPE,3)								OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT_PER_DISTRICT DESC)	AS FREQ_CRIME_TYPE_3,
		NTH_VALUE(CRIMES_OF_TYPE_COUNT_PER_DISTRICT,3)		OVER (PARTITION BY DISTRICT ORDER BY CRIMES_OF_TYPE_COUNT_PER_DISTRICT DESC) 	AS CRIMES_OF_TYPE_COUNT_PER_DISTRICT_3
	FROM (
		SELECT
			STAT_PER_DISTRICT.DISTRICT 										AS DISTRICT,
			STAT_PER_DISTRICT.CRIMES_TOTAL_PER_DISTRICT						AS CRIMES_TOTAL_PER_DISTRICT,
			STAT_PER_DISTRICT.AVG_CRIME_LATITUDE_PER_DISTRICT				AS AVG_CRIME_LATITUDE_PER_DISTRICT,
			STAT_PER_DISTRICT.AVG_CRIME_LONGITUDE_PER_DISTRICT				AS AVG_CRIME_LONGITUDE_PER_DISTRICT,
			CRIME_CODES.name												AS CRIME_TYPE,
			COUNT(crimes.INCIDENT_NUMBER) 									AS CRIMES_OF_TYPE_COUNT_PER_DISTRICT
		FROM (SELECT IF(DISTRICT LIKE '', 'UNKNOWN', DISTRICT) AS DISTRICT, INCIDENT_NUMBER AS INCIDENT_NUMBER, OFFENSE_CODE AS OFFENSE_CODE FROM crimes) AS crimes
		LEFT JOIN codes AS CRIME_CODES ON CRIME_CODES.code=crimes.OFFENSE_CODE
		LEFT JOIN (
			SELECT
				crimes.DISTRICT												 AS DISTRICT,
				COUNT(INCIDENT_NUMBER) 										 AS CRIMES_TOTAL_PER_DISTRICT,
				AVG(Latitude)												 AS AVG_CRIME_LATITUDE_PER_DISTRICT,
				AVG(Longitude)												 AS AVG_CRIME_LONGITUDE_PER_DISTRICT
			FROM (SELECT IF(crimes.DISTRICT LIKE '','UNKNOWN',crimes.DISTRICT) AS DISTRICT, INCIDENT_NUMBER, OFFENSE_CODE,Latitude,Longitude FROM crimes) AS crimes  						
			GROUP BY DISTRICT
		) AS STAT_PER_DISTRICT ON STAT_PER_DISTRICT.DISTRICT LIKE crimes.DISTRICT 
		GROUP BY DISTRICT, CRIMES_TOTAL_PER_DISTRICT, AVG_CRIME_LATITUDE_PER_DISTRICT, AVG_CRIME_LONGITUDE_PER_DISTRICT, CRIME_TYPE		
	) AS STAT_PER_DISTRICT_AND_CRIME_TYPES	
) AS STAT_TOTAL
WHERE FREQ_CRIME_TYPE_2 IS NOT NULL AND FREQ_CRIME_TYPE_3 IS NOT NULL

SELECT REGEXP_REPLACE('aasdkah - asdasd','\s*-.*','')


